#!/bin/bash

name=georgeweigt.github.io

openssl ecparam -out key.pem -name secp384r1 -genkey
openssl req -new -key key.pem -out csr.pem -subj "/O=$name/CN=$name"
openssl x509 -req -days 3650 -in csr.pem -signkey key.pem -out cert.pem

# convert to DER for dumpasn1
#openssl x509 -in cert.pem -inform PEM -out cert.der -outform DER
#openssl ec -in key.pem -inform PEM -out key.der -outform DER

# print cert
#openssl x509 -in cert.pem -noout -text
