#!/bin/bash

name=georgeweigt.github.io

openssl genrsa -out key.pem 2048
openssl req -new -key key.pem -out csr.pem -subj "/O=$name/CN=$name"
echo -e "basicConstraints=critical,CA:true,pathlen:0\nsubjectAltName=DNS:$name" >ext.tmp
openssl x509 -req -days 3650 -in csr.pem -signkey key.pem -out cert.pem -extfile ext.tmp
rm ext.tmp

# convert to DER for dumpasn1
#openssl x509 -in cert.pem -inform PEM -out cert.der -outform DER
#openssl rsa -in key.pem -inform PEM -out key.der -outform DER

# print cert
#openssl x509 -in cert.pem -noout -text
